indigo/blender/Dockerfile, indigo/eva/Dockerfile
blender api messages needed to be built.
=> Eva build fixes

indigo/eva/Dockerfile, indigo/eva/scripts/eva.sh
Eva can now track faces.  Note, however, the eye-gaze direction is still wonky: see https://github.com/hansonrobotics/blender_api/issues/54
=> Perception-node fixes

README.md, opencog/base/Dockerfile, opencog/base/Dockerfile-utopic, opencog/docker-build.sh, opencog/docker-compose.yml, opencog/relex/Dockerfile
the changes make it a bit easier for setting up for relex development and for working on the dialogue system
=> Add relex to docker-compose

opencog/docker-compose.yml
add pythonpath environment variable
=> add pythonpath

opencog/base/Dockerfile
https://github.com/opencog/opencog/pull/1577
https://github.com/opencog/opencog/pull/1579
=> updates accounting the installation script changes

opencog/docker-compose.yml
For non time-traveling git commits
=> sync time in container with host time

opencog/README.md, opencog/docker-build.sh, opencog/docker-compose.yml, opencog/postgres/Dockerfile, opencog/postgres/configure.sh
Speeds up the start of postgres image.  It still needs additional configration for speeding atom-save speed. But suffices for ci testing.
=> Add opencog/postgres image

README.md, indigo/README.md, indigo/base/run.sh, indigo/blender/run.sh, indigo/docker-cleanup.sh, indigo/eva-ros/Dockerfile, indigo/eva-ros/run.sh
Turns out Docker and ROS are not friends with each other.  No matter what the ROS tutorials say.
=> Book report on yesterdays work

indigo/README.md
=> spell check

buildbot/workspace/Dockerfile, opencog/base/Dockerfile
and miscellaneous buildbot update
=> fix building error with opencog/opencog-deps

indigo/eva-opencog/Dockerfile, indigo/eva-opencog/README.md, indigo/eva-opencog/scripts/eva.sh, indigo/ros-base/Dockerfile, indigo/ros-base/scripts/.vimrc, indigo/ros-opencog/Dockerfile
The behavior module now has an install step, else it won't work.
=> Refactoring for Eva behavior.

indigo/ros-base/Dockerfile, indigo/ros-blender/Dockerfile, indigo/ros-incog-blender/Dockerfile
Install blender version 2.71, otherwise gestures don't work.
=> Blender model does not work with version 2.75

opencog/postgres/Dockerfile, opencog/postgres/run.sh
Implement performance tweaks suggested at https://github.com/opencog/atomspace/tree/master/opencog/persist/sql#performance-tweaks independent of the host system.
=> performance tweaks to opencog/postgres

opencog/docker-build.sh, opencog/minecraft.yml, opencog/minecraft/Dockerfile, opencog/minecraft/ros_entrypoint.sh
This PR introduces versions for the docker container to baseline against Spock, Minecraft 1.8.8 and add tmuxinator to improve management of ros nodes.
=> OC2MC Stabilization and better TMUX management

opencog/docker-compose.yml, opencog/postgres/run.sh
@pennachin as per https://github.com/opencog/docker/pull/98#issuecomment-224263058
=> add environment variable for switching on postgres host-specific optimizations.

opencog/relex/Dockerfile
From https://github.com/opencog/relex/pull/245
=> update opennlp link used for opencog/relex

opencog/README.md, opencog/perception/Dockerfile
For machine learning using tensorflow on gpu
=> Add perception image

.gitignore, README.md, buildbot/README.md, buildbot/cronjobs.sh, buildbot/docker-compose.yml, buildbot/master/master.cfg, buildbot/master/run.sh, buildbot/slaves/latest/run.sh, indigo/ros-opencog/Dockerfile, indigo/ros-opencog/scripts/unit-test.sh, jenkins/atomspace_config.xml, jenkins/cogutils_config.xml, jenkins/moses_config.xml, jenkins/scripts/ci-test-atomspace.sh, jenkins/scripts/ci-test-cogutils.sh, jenkins/scripts/ci-test-moses.sh, opencog/README.md, opencog/cogserver/Dockerfile, opencog/cogutils/Dockerfile, opencog/docker-build.sh, opencog/docker-compose.yml, opencog/moses/Dockerfile, opencog/tools/cli/Dockerfile, opencog/tools/ide/Dockerfile, opencog/windows-run.sh
Related to https://github.com/opencog/cogutil/issues/90
=> Rename cogutils to cogutil

opencog/README.md, opencog/base/Dockerfile, opencog/tools/cli/Dockerfile
This installs opencog and byobu
=> Update to images for smoother developer usage

opencog/base/Dockerfile
ocpkg change: https://github.com/opencog/ocpkg/pull/145
=> an update due to changes in ocpkg

.github/workflows/publish-images.yml
This was requested by a community member
=> Add 'latest' tag to published opencog/opencog-dev image

opencog/docker-build.sh
=> Docker won't run if docker not installed!

opencog/relex/Dockerfile
Perhaps this cures the problem
=> Fix the relex docker file to use the correct sort order

opencog/cogserver/Dockerfile
This might fix issue #157.
Not yet tested.
=> Fix the old, broken docker file for cogserver.

opencog/README.md, opencog/common.yml
This fixes issue #151.
It also removes obsolete, unused port 18001.
=> Macos localtime

opencog/bap/Dockerfile
Takes a few hours to build :-(
=> Raw container with just the atomspace, and bap on it, nothing else.

noetic/README.txt, noetic/eva-ros/Dockerfile, noetic/eva-ros/README.md, noetic/eva-ros/build.sh, noetic/eva-ros/run.sh, noetic/eva-ros/scripts/eva.sh, noetic/eva-ros/stop.sh, noetic/ros-base/Dockerfile, noetic/ros-base/README.md, noetic/ros-base/build.sh, noetic/ros-base/run.sh, noetic/ros-base/scripts/.vimrc, noetic/ros-base/stop.sh, noetic/ros-blender/Dockerfile, noetic/ros-blender/README.md, noetic/ros-blender/build.sh, noetic/ros-blender/run.sh, noetic/ros-blender/stop.sh, noetic/ros-opencog/Dockerfile, noetic/ros-opencog/README.md, noetic/ros-opencog/build.sh, noetic/ros-opencog/run.sh, noetic/ros-opencog/scripts/.guile, noetic/ros-opencog/scripts/install-ubuntu-relex.sh, noetic/ros-opencog/scripts/tmux.sh, noetic/ros-opencog/scripts/unit-test.sh, noetic/ros-opencog/stop.sh
Hi Linas, this is just to get the eva-ros half-way building. it is missing the 3 libs, they're commented out in noetic/eva-ros/Dockerfile so that it builds through. I don't know atm where to get those missing libs, and haven't looked at the code to see how I could code around them. I thought you probably know better how to handle it from here. 
One question I have: How do the Eva png files in the indigo folder get referenced? I did not run into any reference to them. 
Blender 2.79 is coming up but on my system the background is annoyingly transparent.
=> Roadmap 1. See noetic/README.txt

noetic/README.txt, noetic/eva-ros/Dockerfile, noetic/eva-ros/scripts/sophia.sh, noetic/ros-base/Dockerfile, noetic/ros-blender/Dockerfile, noetic/ros-opencog/Dockerfile
the pi_vision component of 'eva-ros' docker is working. (webcam comes up, blender with Sophia head comes up).
=> fix up install so that python runs and Sophia head is loaded

noetic/README.txt, noetic/eva-ros/Dockerfile, noetic/eva-ros/run.sh, noetic/ros-opencog/Dockerfile
note, atomspace-rocks is not being built yet.
=> added atomspace-rocks, fixed build issue with link-grammar and flex
